version: "3"
services:
  zkapi:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/dist.Dockerfile
    ports:
     - "3000:3000"
    dns: 223.5.5.5
    environment:
      NODE_ENV: development
    links:
      - swagger
  swagger:
    restart: always
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /docs/api.json
    volumes:
      - ../docs:/docs
  redis:
    restart: always
    image: redis